# ELEGIMOS LA IMAGEN BASE
FROM python:3.10-slim

# CREAMOS EL DIRECTORIO DE TRABAJO
WORKDIR /app

# INSTALAMOS LAS DEPENDENCIAS
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# COPIAMOS EL CODIGO FUENTE
COPY . .

# CONFIGURAMOS PYTHONPATH
ENV PYTHONPATH=/app

# CONFIGURAMOS LA BASE DE DATOS
ENV DATABASE_URL=sqlite:///tasks.db

# CREAMOS EL ARCHIVO DE BASE DE DATOS Y CONFIGURAMOS PERMISOS
RUN touch tasks.db && \
    chmod 666 tasks.db && \
    chmod -R 777 /app

# EXPONEMOS EL PUERTO
EXPOSE 8000

# SCRIPT DE INICIO
COPY start.sh .
RUN chmod +x start.sh

# EJECUTAMOS LA APLICACION
CMD ["/app/start.sh"]
